### ISSUE TITLE
Abstract out Stream Client so that it can be used with other Stream services.

### ISSUE THREAD

**Issue by xsahil03x** [GetStream/stream-chat-dart#39]
The current `Client` is tighly coupled with Stream `Chat services` and `Api's`. It will be better if we can have one `Base Stream Client` which can be directly used for other Stream Services like `Feeds`.

**Comment by KieranLafferty** [comment]
Should also do this on stream_chat_flutter. There's some useful things in there but I had to remove it because it has too many dependencies on things like file_picker, images etc which would be better places in the examples project to keep the library as stream focused as possible without having to adopt so many other deps to use it
